general {
    lock_cmd = pidof hyprlock || /usr/bin/hyprlock
    before_sleep_cmd = loginctl lock-session
    # Adding a small delay or a force-on here helps some hardware
    after_sleep_cmd = hyprctl dispatch dpms on && brightnessctl -r
}

# 2. DIM (2 min)
listener {
    timeout = 120
    on-timeout = brightnessctl -s set 10%
    on-resume = brightnessctl -r
}

# 3. LOCK (5 min)
listener {
    timeout = 300
    on-timeout = loginctl lock-session
}
# 4. SUSPEND (10 min)
listener {
    timeout = 600
    on-timeout = systemctl suspend
    on-resume = hyprctl dispatch dpms on
}
